version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ../nginx/stage.conf:/etc/nginx/nginx.conf:ro
    command: ['nginx-debug', '-g', 'daemon off;']
    ports:
      - 80:80
  web-backend:
    build: ../../web_backend
    ports:
      - 5000:5000
    volumes:
      - ../../web_backend:/iu/web_backend:ro
      - ../../cl:/iu/cl:ro
      - ../server-config/stage.yml:/etc/iu-web-backend.yml:ro
    environment:
      - PYTHONPATH=/iu
    command: ['python', 'server.py']
    stdin_open: true
    tty: true
  mongodb:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb